
## for windows

default : simple2

CFLAGS  = -I SDL/include/ -I /usr/include/mingw -I /usr/local/lib
LDFLAGS = -L /usr/local/lib -lmingw32 -lSDL

# test.o : test.c makefile
# 	gcc -mno-cygwin -Duuuzzz=SDL_main -c test.c $(CFLAGS) -o test.o

win32main.o : win32main.c makefile
	gcc -mno-cygwin -c win32main.c $(CFLAGS) -o win32main.o

MLTON_FLAGS = @MLton max-heap 200m --

ctest : test.o win32main.o
	gcc -L/usr/local/lib -lmingw32 -lSDL -mno-cygwin -mwindows test.o win32main.o -o ctest
# -L/usr/local/lib -L /lib/mingw - -lmingw32 -lSDL

test : test.sml test.o
	mlton $(MLTON_FLAGS)  -cc-opt -Dmain=WhatEverMain -link-opt "-L/usr/local/lib -L /lib/mingw -lmingw32 -lcrtdll -lSDL" test.cm test.o win32main.o


simple.o : simple.c
	gcc -c -I SDL/include/ simple.c -o simple.o

simple : simple.o
	gcc `SDL/sdl-config --libs` simple.o -o simple

# -L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mno-cygwin -mwindows
simple2 : test.o
	mlton $(MLTON_FLAGS) -cc-opt "`SDL/sdl-config --cflags`" -link-opt "`SDL/sdl-config --libs`" test.o

test.o : test.c makefile
	gcc -c `SDL/sdl-config --cflags` test.c -o test.o
