
default : game.exe


sdlml.o : ../sdlml/sdlml.c
	gcc -DLINUX -O `sdl-config --cflags` -c ../sdlml/sdlml.c -o sdlml.o

game.exe : sdlml.o *.sml makefile
	mlton -link-opt "-lSDL_image -ltiff -lpng -ljpeg -lz `sdl-config --libs`" -default-ann 'allowFFI true' -output game.exe game.cm sdlml.o

clean :
	rm -f core core.* *~ *.exe *.o
